CREATE DATABASE `blog-test-task`;

CREATE TABLE Posts
(
    `userId` INTEGER NOT NULL,
    `id` INTEGER AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(50) NOT NULL,
    `body` TEXT(268) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE Comments
(
    `postId` INTEGER NOT NULL,
    `id` INTEGER AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL,
    `email` VARCHAR(50) NOT NULL,
    `body` TEXT(268) NOT NULL
)ENGINE = InnoDB;
